services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3309:3306
  adminer:
    image: adminer
    # Credentials:
    # server: mysql
    # user:root
    restart: always
    ports:
      - 8080:8080